services:
  db:
    image: postgres:15
    container_name: diary_db
    restart: always
    environment:
      POSTGRES_DB: diary_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d diary_db"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  app:
    image: aditya152077/fastapi-postgres-diary-api
    container_name: diary_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/diary_db
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports

volumes:
  postgres_data:
